services:
  postgres:
    image: "postgres"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - wishlist_pg_data:/var/lib/postgresql/data
  app:
    build: .
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  wishlist_pg_data:
